spring:
  application:
    name: binbean_BE

  jpa:
    hibernate:
      ddl-auto: update # jpa? ??? ???? ???? db ???? ???? ????
    show-sql: true

jwt:
  secret-key: YmluYmVhbi1zZWF0cy1maW5kZXItZm9yLWNhZmUtYXV0aG9yaXphdGlvbgo=
  token:
    access-expiration-time: 10800000 # 3??
    refresh-expiration-time: 604800000 # 7?