spring:
  application:
    name: binbean_BE

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/binbean
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: binbean
    password: 1111


jwt:
  secret-key: YmluYmVhbi1zZWF0cy1maW5kZXItZm9yLWNhZmUtYXV0aG9yaXphdGlvbgo=
  token:
    access-expiration-time: 10800000 # 3시간
    refresh-expiration-time: 604800000 # 7일

data:
  redis:
    host: localhost # 로컬 테스트 시
    port: 6379